### PR TITLE
Minor tweeks

### PR DESCRIPTION
**Pull request by David132639**
Minor changes, as described in commit messages

### CODE REVIEW

**Comment by gdcodes** [comment]
Great idea to change the GUTS logo depending on the event date! The past event icon for CO also looks better with the torch design. Checked on Safari and Google Chrome (including on small screens using dev tools) with no issues. LinkedIn page sharing is optional, @Just-Q3 is it okay to share your page or would another page or none be preferable?

**Comment by David132639** [comment]
> 
> 
> Great idea to change the GUTS logo depending on the event date! 
Not my idea 😄 was already done with the old old logo

**Comment by gdcodes** [comment]
> > Great idea to change the GUTS logo depending on the event date!
> 
> Not my idea 😄 was already done with the old old logo

Ah I see it was done for the original GUTS logo. Thanks for implementing that for pre-2020 logo!

**Review by Just-Q3 — COMMENTED** [review]
Looks good, are we going to keep it so that every 5 years we include a new tab? Since I see that you added 2015, and 2020.

**Comment by David132639** [comment]
> 
> 
> Looks good, are we going to keep it so that every 5 years we include a new tab? Since I see that you added 2015, and 2020.

Whenever there is a new GUTS logo 😄

**Review by gdcodes — APPROVED** [review]

**Comment by Just-Q3** [comment]
Delete the develop branch? There are no unsaved changes?

**Pull request merged**
